version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:${PORT}"
    networks:
      - candy-shop-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"
    networks:
      - candy-shop-network

networks:
  candy-shop-network:
    driver: bridge
