version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
